version: '3.0'

services:
  frontend:
    image: yordanganev/forum_fe:latest
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    image: yordanganev/forum_be:latest
    container_name: backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8090:8090"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
